framework:
    messenger:

        transports:
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                retry_strategy:
                    max_retries: 0

        routing:
            'App\Message\CreateBookMessage': async
